config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "https://navigating-canada-dev.herokuapp.com"

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :mailing_lists
    resources :users
    resources :conversations
  end

  resources :users
  resources :sessions
  resources :mailing_lists
  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :conversations do
    resources :messages
  end
  resources :pages
  resources :reset_passwords, only: [:new, :create, :update, :edit]
  resources :stories

  resources :posts do
    resources :upvotes, only: [:create, :destroy]
  end

  resources :posts do
    resources :downvotes, only: [:create, :destroy]
  end

  scope "(:locale)", :locale => /en|fr/ do

    # page
      root 'sessions#log_in'

      get '/content',to: 'pages#content', as: :content

      get '', to: 'pages#index', as: :index

      get '/timeline', to: 'pages#timeline', as: :timeline

      get '/chat_admin', to: 'pages#chat_admin', as: :chat_admin

      get '/stopConversation', to: 'pages#stopConversation', as: :stop_conversation


    #users

      get '/profile/edit', to: 'users#profile_edit', as: :profile_edit

      get '/profile', to: 'users#profile_show', as: :profile


    #sessions

      post '/log_in', to: 'sessions#create', as: :sessions_create

      get '/log_in', to: 'sessions#log_in', as: :log_in

      delete '/log_out', to: 'sessions#destroy', as: :log_out

      get '/log_out', to: 'sessions#log_out', as: :my_log_out


    #forums

      mount Thredded::Engine => '/forum'

      get '/forum',to: 'pages#forum', as: :forum

      get '/forum/preferences/edit', as: :notification_edit

       post "oauth/callback" => "oauths#callback"
       get "oauth/callback" => "oauths#callback" # for use with Facebook
       get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
     # delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

      root 'todos#index'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  include ActionController::RequestForgeryProtection
  include ResetPasswordsHelper

  protect_from_forgery with: :exception, unless: -> { request.format.json? }
  skip_before_filter :require_login
  skip_before_filter :verify_authenticity_token

  def new
  end

  def protect_from_forgery
    false
  end

  def create
    say_no_to_protect_against_forgery!
    @user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    reset_password_email(@user)
    say_no_to_protect_against_forgery!
    flash[:success] = 'Instructions have been sent to your email.'
    redirect_to log_in_path
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated && return if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      flash[:success] = 'Password was successfully updated.'
      redirect_to log_in_path
    else
      render "edit"
    end
  end

  def say_no_to_protect_against_forgery!
    _helpers.module_eval do
      def protect_against_forgery?
        false
      end
    end
  end

end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
  require 'sendgrid-ruby'
  include SendGrid

  def reset_password_email(user)
    @user = user
    @url  = edit_reset_password_url(@user.reset_password_token)

    from = Email.new(email: 'janet.audu@navigatingcanada.com')
    to = Email.new(email: user.email)
    subject = "Your password has been reset"
    content = Content.new(type: 'text/html', value: '<p>Hello, ' + @user.name + '</p>
                <p>Someone (hopefully, you) have requested to reset your password.</p>
                <p>To choose a new password, follow this link: ' + @url + '</p>')
    mail = Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: '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')
    response = sg.client.mail._('send').post(request_body: mail.to_json)
    puts response.status_code
    puts response.body
    puts response.headers
  end
end

app/views/reset_passwords/edit.html.erb
<div class="page-header">
  <div id="profileTitle">
    <h1 class="text-center"><%= t(".title") %></h1>
  </div>
</div>

<div class="signup">
  <%= form_for @user, url: reset_password_path(@token), method: :patch do |f| %>

      <div class="form-group col-md-6 col-sm-offset-3">
        <%= f.label t(".password") %>
        <%= f.password_field :password, class: 'form-control', required: true %>
      </div>

      <div class="form-group col-md-6 col-sm-offset-3">
        <%= f.label t(".password_confirmation") %>
        <%= f.password_field :password_confirmation, class: 'form-control', required: true%>
      </div>

      <div class="form-group form-button col-md-2 col-md-offset-5" style="text-align: center;">
        <%= f.submit t(".set_password"), class: 'btn red-standard-btn', style: 'margin:40px 0;' %>
      </div>
  <% end %>
</div>

app/views/reset_passwords/new.html.erb
<div class="page-header">
  <div id="profileTitle">
    <h1 class="text-center"><%= t(".title") %></h1>
  </div>
</div>

<div class="signup">
  <%= form_tag reset_passwords_path, method: :post do %>

      <div class="form-group col-md-6 col-sm-offset-3">
        <%= label_tag t(".email") %>
        <%= email_field_tag :email, nil, class: 'form-control', required: true %>
      </div>

      <div class="form-group form-button col-md-2 col-md-offset-5" style="text-align: center;">
        <%= submit_tag t(".send_reset") , class: 'btn red-standard-btn', style: 'margin:40px 0;' %>
      </div>
  <% end %>
</div>